# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffb6aef2df5423cfed182c7e91af72f41143888579a6afe8f11bd03bd286f24c3f8075056c8da34657e4e7c9103f0dce1c0118732c233c2d44dbca29705ec52b

test:
  secret_key_base: b954dcd06dcf059d5d09a25377bdb61862737af48abcafc69799f0f3b86981a70d2886f13b59f637c4142c6ea8bd728c9fee7597ab48eb87fecacdd296a92f24

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
